version = 0.1

[default.deploy.parameters]
stack_name = "zt-radar-stack"
resolve_s3 = true
s3_prefix = "zt-radar-stack"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DiscordPublicKey=\"02b51d194a836f3bab5592028a98736866a22ec1f9c6fa1f6cfa43b7df48b20a\" DiscordAppId=\"1537623174211182712\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
